services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evernight
    environment:
      - NODE_OPTIONS=--max-old-space-size=512
    env_file:
      - .env
    depends_on:
      - redis
    command: npm start
  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/redis_data

volumes:
  redis_data:
